RegisterNetEvent('addweapon:airdrop', function()
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.addWeapon('WEAPON_DOUBLEACTION', 48)
	xPlayer.addInventoryItem('clip', 5)
	xPlayer.addInventoryItem('medikit', 4)
	xPlayer.addInventoryItem('painkiller', 5)
	xPlayer.addInventoryItem('helm3', 2)
	xPlayer.addInventoryItem('repairkit', 2)	
	xPlayer.addInventoryItem('armor2', 4)
end)

RegisterNetEvent("addweapon:pistol", function()
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.addWeapon('WEAPON_PISTOL50', 48)
    xPlayer.addWeapon('WEAPON_REVOLVER_MK2', 0)
end)