-- // pgg \\ --
RegisterNetEvent('pgg:manual', function(title, msg, sec)
	ESX.Scaleform.ShowFreemodeMessage(title, msg, sec)
end)

RegisterNetEvent('pgg:otomatis', function()
	ESX.Scaleform.ShowFreemodeMessage('10', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('9', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('8', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('7', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('6', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('5', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('4', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('3', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('2', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('1', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('GO!', '~r~Royal Battleground', 1)
	Wait(500)
	ESX.Scaleform.ShowFreemodeMessage('GOOD LUCK HAVE FUN!!', '~r~Royal Battleground', 4)
end)